services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: kaleid-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: 12345678
      MONGODB_INITDB_DATABASE: kaleid
    volumes:
      - mongodb_data:/data/db
    networks:
      - kaleid
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: kaleid-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://admin:12345678@kaleid-mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 12345678
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - kaleid

volumes:
  mongodb_data:
    name: kaleid-mongodb-data

networks:
  kaleid:
    external: true
