services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/sources/__pycache__
      - /app/processors/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1\
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5678:5678" # para debugging
    networks:
      - kaleid

networks:
  kaleid:
    external: true
