services:
  kaleid-collector:
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: kaleid-collector
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/sources/__pycache__
      - /app/processors/__pycache__
    networks:
      - kaleid-network
networks:
  kaleid-network:
    external: true
